// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_IO-sdacyBI5AVeIhniRRrGks8oVl-tY',
    appId: '1:950912931300:web:7519a63f4a6f1807f2a3f1',
    messagingSenderId: '950912931300',
    projectId: 'petcompanion-133d9',
    authDomain: 'petcompanion-133d9.firebaseapp.com',
    storageBucket: 'petcompanion-133d9.firebasestorage.app',
    measurementId: 'G-9FMK7PYK5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaPGkQKHwojV9tmDnxE5rff6e_zV6BBKk',
    appId: '1:950912931300:android:8cf5016fb28a2e5bf2a3f1',
    messagingSenderId: '950912931300',
    projectId: 'petcompanion-133d9',
    storageBucket: 'petcompanion-133d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYbWDhgtqNeGC7lD2XXlAL4j2a215mfRA',
    appId: '1:950912931300:ios:1c32400df244ba3af2a3f1',
    messagingSenderId: '950912931300',
    projectId: 'petcompanion-133d9',
    storageBucket: 'petcompanion-133d9.firebasestorage.app',
    iosClientId: '950912931300-q20u93j50kuf20f4c492nkkhcuuq5ouh.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYbWDhgtqNeGC7lD2XXlAL4j2a215mfRA',
    appId: '1:950912931300:ios:1c32400df244ba3af2a3f1',
    messagingSenderId: '950912931300',
    projectId: 'petcompanion-133d9',
    storageBucket: 'petcompanion-133d9.firebasestorage.app',
    iosClientId: '950912931300-q20u93j50kuf20f4c492nkkhcuuq5ouh.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_IO-sdacyBI5AVeIhniRRrGks8oVl-tY',
    appId: '1:950912931300:web:6d4659992994b19af2a3f1',
    messagingSenderId: '950912931300',
    projectId: 'petcompanion-133d9',
    authDomain: 'petcompanion-133d9.firebaseapp.com',
    storageBucket: 'petcompanion-133d9.firebasestorage.app',
    measurementId: 'G-BK8Q4JVEXJ',
  );
}
